### ISSUE TITLE
Does not build for arm64 without changes to Dockerfile

### ISSUE THREAD

**Issue by Outshynd** [craumix/jmb-container#10]
I had to change the first line of the Dockerfile `FROM eclipse-temurin:11-jre-alpine` to `FROM eclipse-temurin:11-jre` to get the container to build on arm64. Pretty simple change that I'm documenting here for anyone that wants to use this container with linux/arm64/v8 architechture.

**Comment by soguertler** [comment]
There should be some way to use the `TARGETARCH` build variable to use alpine for amd64 and the default for the remaining architectures. [Docker build docs](https://docs.docker.com/build/building/variables/#pre-defined-build-arguments)

**Comment by afwolfe** [comment]
I also build this image for use on arm64, and it looks like eclipse-temurin doesn't provide arm64 alpine binaries for JDK 11: https://github.com/docker-library/official-images/issues/15762

For a multi-platform base image, this project would need to use the Ubuntu `11-jre` tag or install Oracle OpenJDK into a generic Alpine base. I submitted a PR to do the latter in #11.

**Comment by soguertler** [comment]
Should be solved with latest commit. Please let me know if you have any issues with my changes.
