### ISSUE TITLE
Needs update to /jagrosh/MusicBot/releases/tag/0.4.2 to fix 403 when playing videos

### ISSUE THREAD

**Issue by Snailpower** [craumix/jmb-container#13]
Hi, first of all a big thanks for making this a great container.

I noticed that you do not have the newest 0.4.2 version of /jagrosh/MusicBot available as a tag yet. Got released about an hour ago.

Maybe a variable while running your container is a good option for users to switch instead of waiting for your container? Something like 

services:
  jmusicbot:
    image: craumix/jmusicbot
    container_name: jmusicbot
    restart: unless-stopped
    volumes:
     - ./config:/jmb/config
     **jmusic_source_version: 0.4.2**

**Comment by soguertler** [comment]
Update to 0.4.2 is done, while setting the version trough env is theoretically possible it would be a really uncommon approach for containers. 
Building trough actions is pretty simple now so I'll just need to find someone who can also manually trigger the action on updates or just run it on a cron and check for the latest version on a schedule.

**Comment by Snailpower** [comment]
Great, thanks! Would be a weird edge case indeed. Was just wondering if it would be possible because of my unraid setup, simple plug-and-play for dockerimages where I then could just set the version variable.

Probably better to automate releases from a cron that checks for versions and keep using docker tags like you said :)
