### ISSUE TITLE
Versions >0.4.0 lose playlist controls

### ISSUE THREAD

**Issue by clockwinder** [craumix/jmb-container#14]
After updating from `v0.4.0` to `v0.4.1` or `v0.4.2`, I lose the ability to make/modify/remove playlists which I previously had access to.

Rolling back to `v0.4.0` restores this functionality.

The docker log has no entries on any of these failures.

Is there more info I can provide?  Can anyone else confirm if they're having this issue?

**Comment by soguertler** [comment]
Related to #15, run `chown -R 10000:10001 ./config` to allow the container to write to the config directory.
