### ISSUE TITLE
Non-root user is unable to write to config volume

### ISSUE THREAD

**Issue by afwolfe** [craumix/jmb-container#15]
I had some time to test the reimplementation #12 and I think there is still a gap in the entrypoint to ensure ownership of the files and/or the documentation for how to work with the non-root user manually.

With my current config volume, the appuser had permission to read the existing config.txt but was unable to create the new serversettings.json:
```
[19:48:49] [INFO] [JMusicBot]: Loaded config from /jmb/config/config.txt
[19:48:49] [INFO] [Settings]: serversettings.json will be created in /jmb/config/serversettings.json
[19:48:49] [WARN] [Settings]: Failed to create new settings file: java.nio.file.AccessDeniedException: serversettings.json
[19:48:50] [INFO] [JDA]: Login Successful!
[19:48:50] [INFO] [JMusicBot]: JMusicBot
[19:48:50] [INFO] [WebSocketClient]: Connected to WebSocket
[19:48:50] [INFO] [JDA]: Finished Loading!
```
A similar failure occurs and the config.txt is unable to be written if the user starts the container interactively and attempts to configure it by hand for the first time.

It can be worked around by granting all permissions on the volumes or chowning to the container's IDs (`10000:10001`).

#14 may also be related if the appuser does not have sufficient permissions on a playlist volume.

**Comment by soguertler** [comment]
Optimally you'd run `chown 10000:10001` on the files, so that the MusicBot can edit them. 
I don't really see another way to secure the container process while being able to keep the files on the host, since otherwise the container would have to run as root/system user or the file would have to be writeable by everyone. 

Should probably add this in the readme.

**Comment by clockwinder** [comment]
If possible, I would prefer how linuxserver.io handles this, which is allowing the user to select UID/GID via environmental variables.

**Comment by soguertler** [comment]
you should still able to override the user by specifying the attribute for the container (though you probably shouldn't and instead `chown` the files instead because thats more secure). <https://docs.docker.com/reference/compose-file/services/#user>

Example:

```yaml
services:
  musicbot:
    user: 1000:1000
```

**Comment by clockwinder** [comment]
That works like a charm, thank you!
