### ISSUE TITLE
cannot get to successfully build in docker

### ISSUE THREAD

**Issue by amalgamemnon** [craumix/jmb-container#7]
I cannot get this to successfully build in docker after it's been updated to use 0.4.0 of jmb.  Please reach out if you have time.

**Comment by amalgamemnon** [comment]
Instructions on the edits that need to be made to docker-compose.yaml to properly build and compose would be super helpful.

**Comment by soguertler** [comment]
The provided docker-compose file is not supposed to build, it should only run the prebuilt image.
If you still want to build the container yourself you can just run `docker build .`
