### ISSUE TITLE
musicbot needs fork or 0.4.1 to play youtube again

### ISSUE THREAD

**Issue by livehifi** [craumix/jmb-container#8]
due to youtube's changes the ios/mobile player version the bot uses no longer works. the WEB style playback works, and lavalink-devs are working on fixing that. i believe the fix is in a new distribution so jmusicbot maintainers need to change to that dependency. there is a post about it here https://github.com/jagrosh/MusicBot/pull/1552

either the fork listed there, or 0.4.1 when it releases will fix the bot playing youtube again. hope that helps!

**Comment by soguertler** [comment]
version updated to 0.4.1 so this should be solved
